### ISSUE TITLE
`certificate verify failed` during SmartConnect on python 2.7.6

### ISSUE THREAD

**Issue by rajalokan** [vmware/pyvmomi#330]
Hi Guys,

I'm trying to make a connection against my vSphere instance like this
```
from pyVim import connect
connect.SmartConnect(
            protocol="https",
            host=<my_host>,
            user=<my_user>,
            pwd=<my_pass>,
        )
```
but it gives
`[Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed`

I can get it working in python 2.7.9+ with passing a `ssl._create_unverified_context()` but that is just temporary. Can anyone please suggest what is the correct approach to get it working on python 2.7.6 (for Ubuntu 14.04).

**Comment by aryaanand** [comment]
This error occurs if you use pyvmomi 6.0. Add the below lines in your code

context = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
context.verify_mode = ssl.CERT_NONE

        self.si = SmartConnect(host=self.host,
                               user=self.user,
                               pwd=self.password,
                               port=int(self.port),
                               sslContext=context)

**Comment by rajalokan** [comment]
@aryaanand This works on python 2.7.9+. Since I'm on python 2.7.6, not an option for me. 

Solution for python 2.7.6 is to use pyvmomi==5.5.0 as suggested by @pwrmiller. Marking this closed.

**Comment by xayangjing** [comment]
`context = ssl._create_unverified_context()
`si` = SmartConnect(host=args.host,
          user=args.user,
          pwd=password,
          port=int(args.port),
        sslContext=context)`

**Comment by Neurobion** [comment]
https://www.python.org/dev/peps/pep-0476/
